### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by danielklecha** [Sicos1977/MSGReader#442]
Hi!

My project is using strong-named assemblies.
Could you modify the deployment to generate two versions of the package?
For example: MSGReader and MSGReader.StrongName.
Do you have plans to do that?

I use GitHub actions for my library and this steps worked for me:

```yaml
    - name: Create Strong Name Assembly Key File
      run: |
        echo "${{ secrets.STRONG_NAME_KEY }}" | base64 --decode > MSGReader.snk

    - name: Build (Strong-Named)
      run: dotnet build MsgReaderCore/MSGReader.csproj --configuration Release --no-restore /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$PWD/MSGReader.snk

    - name: Pack (Strong-Named)
      run: dotnet pack MsgReaderCore/MSGReader.csproj --configuration Release --no-build /p:PackageId=MSGReader.StrongName

    - name: Publish to NuGet
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }}
```

Best regards
